### ISSUE TITLE
Publish a Poll

### ISSUE THREAD

**Issue by STnobile** [STnobile/alove-running#2]
In order to** automatically hide the poll** as an
**administrator**, I can **pick the expiry date while publishing the poll.**

**Comment by STnobile** [comment]
## Acceptance Criteria

* The option should be provided as a checkbox.
* The checkbox should be "checked" by the administrator.
*  The option should appear above the submit button.

**Comment by STnobile** [comment]
## Tasks:

- [ ]  Update the admin module view: the poll design (HTML and CSS) to include
     date picker 
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by STnobile** [comment]
this is completed
